### ISSUE TITLE
Open instead of Create

### ISSUE THREAD

**Issue by peet-brits** [fayras/vscode-simple-new-file#9]
When I want to create a new file, but the new file name is a partial match for an existing file, then it opens the existing file instead of creating a new file.

For example, I have a file named "MyTestFile.txt", and then I try to create another file named "Test.txt"

Is there any way to force it to create a file instead of opening it?

**Comment by fayras** [comment]
This is kind of a limitation of the QuickPick interface, as it always selects the first item by default. From version 1.1.2 on, the input string will be trimmed. You then will be able to append a whitespace ("Test.txt ") which won't match "MyTestFile.txt" anymore but will create the correct "Test.txt" file.

**Comment by davidalejandroaguilar** [comment]
@fayras This doesn't work when doing the same so that a folder doesn't match. e.g. 

* if a file exists in `/app/controllers/admin/seatings_controller.rb` 
* and you want to create a `/app/controllers/admin/seatings/employees_controller.rb`

The QuickPick maches the first file. 

Adding whitespace at the end does not fix it, but adding a whitespace at the end of `/seatings` does. In other words: `/app/controllers/admin/seatings /employees_controlle.rb` fixes it. However, the folder is then named `seatings ` with a space.

Perhaps we should trim the start and end of a folder? Or at least make this configurable?

**Comment by fayras** [comment]
@davidalejandroaguilar I tried to reproduce your case but could not find any issues with it. If the problem persists, could you please elaborate on the steps to reproduce the issue?
